export const GET_NETFLIX_ORIGINALS = 'GET_NETFLIX_ORIGINALS';
export const GET_TRENDING_MOVIES = 'GET_TRENDING_MOVIES';
export const GET_NETFLIX_ORIGINALTVS = 'GET_NETFLIX_ORIGINALTVS';
export const GET_SEARCH_MOVIE = 'GET_SEARCH_MOVIE';
